# ===================================================================
# EVShare 3D Platform - Development Profile ('dev')
# ===================================================================

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.example.evshare: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.flywaydb: DEBUG
