package com.example.evshare.repository;

import com.example.evshare.entity.Vehicle;
import com.example.evshare.entity.enums.VehicleStatus;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@Transactional
@DisplayName("Checkpoint 04-B — Vehicle Persistence & Repository Integration Tests")
class VehicleRepositoryTest {

    @Autowired
    private VehicleRepository vehicleRepository;

    private String generateVin() {
        return "VIN" + UUID.randomUUID().toString().replace("-", "").substring(0, 14).toUpperCase();
    }

    private String generatePlate() {
        return "51G-" + (int)(10000 + Math.random() * 89999);
    }

    private Vehicle buildSampleVehicle(String vin, String plate, VehicleStatus status) {
        Vehicle v = new Vehicle();
        v.setVin(vin);
        v.setLicensePlate(plate);
        v.setModelName("Tesla Model 3 Performance");
        v.setManufacturer("Tesla");
        v.setModel3dAssetPath("models/vehicles/tesla_model_3.glb");
        v.setStatus(status);
        v.setBatteryLevel(95);
        v.setOdometerKm(new BigDecimal("12450.50"));
        v.setStallLocationCode("BAY-01");
        return v;
    }

    @Test
    @DisplayName("1. PK & Metadata: Correctly saves vehicle and generates ID, auditing timestamps")
    void testCreateAndPersistVehicle() {
        String vin = generateVin();
        String plate = generatePlate();
        Vehicle vehicle = buildSampleVehicle(vin, plate, VehicleStatus.AVAILABLE);

        Vehicle saved = vehicleRepository.saveAndFlush(vehicle);

        assertNotNull(saved.getId(), "Vehicle ID must be generated by identity strategy");
        assertEquals(vin, saved.getVin());
        assertEquals(plate, saved.getLicensePlate());
        assertEquals("Tesla Model 3 Performance", saved.getModelName());
        assertEquals("Tesla", saved.getManufacturer());
        assertEquals("models/vehicles/tesla_model_3.glb", saved.getModel3dAssetPath());
        assertEquals(VehicleStatus.AVAILABLE, saved.getStatus());
        assertEquals(95, saved.getBatteryLevel());
        assertEquals(new BigDecimal("12450.50"), saved.getOdometerKm());
        assertEquals("BAY-01", saved.getStallLocationCode());
        assertNotNull(saved.getCreatedAt(), "Auditing createdAt must be automatically populated");
        assertNotNull(saved.getUpdatedAt(), "Auditing updatedAt must be automatically populated");
    }

    @Test
    @DisplayName("2. Default Values: Verifies schema defaults for battery (100), odometer (0.00), and status (AVAILABLE)")
    void testVehicleDefaultValues() {
        Vehicle defaultVehicle = new Vehicle();
        defaultVehicle.setVin(generateVin());
        defaultVehicle.setLicensePlate(generatePlate());
        defaultVehicle.setModelName("VF 8 Plus");
        defaultVehicle.setManufacturer("VinFast");
        defaultVehicle.setModel3dAssetPath("models/vehicles/vf8.glb");

        Vehicle saved = vehicleRepository.saveAndFlush(defaultVehicle);

        assertEquals(VehicleStatus.AVAILABLE, saved.getStatus(), "Default status must be AVAILABLE");
        assertEquals(100, saved.getBatteryLevel(), "Default battery level must be 100%");
        assertEquals(BigDecimal.ZERO, saved.getOdometerKm(), "Default odometer must be 0.00 km");
        assertEquals("BAY-01", saved.getStallLocationCode(), "Default stall location must be BAY-01");
    }

    @Test
    @DisplayName("3. Unique VIN Index: Rejects duplicate VIN with DataIntegrityViolationException")
    void testUniqueVinConstraint() {
        String duplicateVin = generateVin();
        Vehicle v1 = buildSampleVehicle(duplicateVin, generatePlate(), VehicleStatus.AVAILABLE);
        vehicleRepository.saveAndFlush(v1);

        Vehicle v2 = buildSampleVehicle(duplicateVin, generatePlate(), VehicleStatus.AVAILABLE);
        assertThrows(DataIntegrityViolationException.class, () -> {
            vehicleRepository.saveAndFlush(v2);
        }, "Persisting duplicate VIN must trigger unique constraint violation");
    }

    @Test
    @DisplayName("4. Unique License Plate Index: Rejects duplicate license plate with DataIntegrityViolationException")
    void testUniqueLicensePlateConstraint() {
        String duplicatePlate = generatePlate();
        Vehicle v1 = buildSampleVehicle(generateVin(), duplicatePlate, VehicleStatus.AVAILABLE);
        vehicleRepository.saveAndFlush(v1);

        Vehicle v2 = buildSampleVehicle(generateVin(), duplicatePlate, VehicleStatus.AVAILABLE);
        assertThrows(DataIntegrityViolationException.class, () -> {
            vehicleRepository.saveAndFlush(v2);
        }, "Persisting duplicate license plate must trigger unique constraint violation");
    }

    @Test
    @DisplayName("5. Lookup Queries: findByVin, findByLicensePlate, and existence checks")
    void testFindByVinAndLicensePlate() {
        String vin = generateVin();
        String plate = generatePlate();
        Vehicle vehicle = buildSampleVehicle(vin, plate, VehicleStatus.AVAILABLE);
        vehicleRepository.saveAndFlush(vehicle);

        assertTrue(vehicleRepository.existsByVin(vin));
        assertTrue(vehicleRepository.existsByLicensePlate(plate));
        assertFalse(vehicleRepository.existsByVin("NON_EXISTENT_VIN_9999"));
        assertFalse(vehicleRepository.existsByLicensePlate("NON_EXISTENT_PLATE"));

        Optional<Vehicle> byVin = vehicleRepository.findByVin(vin);
        assertTrue(byVin.isPresent());
        assertEquals(plate, byVin.get().getLicensePlate());

        Optional<Vehicle> byPlate = vehicleRepository.findByLicensePlate(plate);
        assertTrue(byPlate.isPresent());
        assertEquals(vin, byPlate.get().getVin());
    }

    @Test
    @DisplayName("6. Status Queries & Counts: findByStatus and countByStatus")
    void testFindByStatusAndCount() {
        Vehicle v1 = buildSampleVehicle(generateVin(), generatePlate(), VehicleStatus.CHARGING);
        Vehicle v2 = buildSampleVehicle(generateVin(), generatePlate(), VehicleStatus.MAINTENANCE);
        Vehicle v3 = buildSampleVehicle(generateVin(), generatePlate(), VehicleStatus.MAINTENANCE);

        vehicleRepository.saveAndFlush(v1);
        vehicleRepository.saveAndFlush(v2);
        vehicleRepository.saveAndFlush(v3);

        List<Vehicle> chargingList = vehicleRepository.findByStatus(VehicleStatus.CHARGING);
        assertTrue(chargingList.stream().anyMatch(v -> v.getId().equals(v1.getId())));

        List<Vehicle> maintenanceList = vehicleRepository.findByStatus(VehicleStatus.MAINTENANCE);
        assertTrue(maintenanceList.stream().anyMatch(v -> v.getId().equals(v2.getId())));
        assertTrue(maintenanceList.stream().anyMatch(v -> v.getId().equals(v3.getId())));

        assertTrue(vehicleRepository.countByStatus(VehicleStatus.MAINTENANCE) >= 2);
    }

    @Test
    @DisplayName("7. Pagination & Sorting: Pageable vehicle queries")
    void testPagedStatusQuery() {
        Vehicle v1 = buildSampleVehicle(generateVin(), generatePlate(), VehicleStatus.IN_USE);
        Vehicle v2 = buildSampleVehicle(generateVin(), generatePlate(), VehicleStatus.IN_USE);
        vehicleRepository.saveAndFlush(v1);
        vehicleRepository.saveAndFlush(v2);

        Page<Vehicle> page = vehicleRepository.findByStatus(
                VehicleStatus.IN_USE,
                PageRequest.of(0, 10, Sort.by(Sort.Direction.DESC, "id"))
        );

        assertNotNull(page);
        assertTrue(page.getTotalElements() >= 2);
        assertTrue(page.getContent().stream().allMatch(v -> v.getStatus() == VehicleStatus.IN_USE));
    }

    @Test
    @DisplayName("8. Manufacturer Case-Insensitive Filter")
    void testFindByManufacturerIgnoreCase() {
        Vehicle v = buildSampleVehicle(generateVin(), generatePlate(), VehicleStatus.AVAILABLE);
        v.setManufacturer("Hyundai");
        vehicleRepository.saveAndFlush(v);

        Page<Vehicle> hyundaiUpper = vehicleRepository.findByManufacturerIgnoreCase("HYUNDAI", PageRequest.of(0, 10));
        assertTrue(hyundaiUpper.getContent().stream().anyMatch(item -> item.getId().equals(v.getId())));

        Page<Vehicle> hyundaiLower = vehicleRepository.findByManufacturerIgnoreCase("hyundai", PageRequest.of(0, 10));
        assertTrue(hyundaiLower.getContent().stream().anyMatch(item -> item.getId().equals(v.getId())));
    }

    @Test
    @DisplayName("9. Stall Location Query: Find vehicles by designated 3D garage bay")
    void testFindByStallLocationCode() {
        String uniqueStall = "BAY-" + UUID.randomUUID().toString().substring(0, 6).toUpperCase();
        Vehicle v = buildSampleVehicle(generateVin(), generatePlate(), VehicleStatus.AVAILABLE);
        v.setStallLocationCode(uniqueStall);
        vehicleRepository.saveAndFlush(v);

        List<Vehicle> stallVehicles = vehicleRepository.findByStallLocationCode(uniqueStall);
        assertEquals(1, stallVehicles.size());
        assertEquals(v.getId(), stallVehicles.get(0).getId());
    }

    @Test
    @DisplayName("10. Auditing Updates: Updating status modifies updatedAt timestamp")
    void testAuditTimestampUpdate() {
        Vehicle v = buildSampleVehicle(generateVin(), generatePlate(), VehicleStatus.AVAILABLE);
        Vehicle saved = vehicleRepository.saveAndFlush(v);

        Instant originalUpdatedAt = saved.getUpdatedAt();

        // Mutate state
        saved.setStatus(VehicleStatus.CHARGING);
        saved.setBatteryLevel(80);
        Vehicle updated = vehicleRepository.saveAndFlush(saved);

        assertEquals(VehicleStatus.CHARGING, updated.getStatus());
        assertEquals(80, updated.getBatteryLevel());
        assertNotNull(updated.getUpdatedAt());
    }
}
