import type { Vector3Tuple } from 'three';
import type { SectorId, UserRole } from './worldTypes';

export interface WorldPortalNode {
  id: string;
  name: string;
  label: string;
  subtitle: string;
  fromSector: SectorId;
  toSector: SectorId;
  position: Vector3Tuple;
  rotation: Vector3Tuple;
  color: string;
  requiredRole?: UserRole;
  isReturnPortal?: boolean;
}

export const PORTAL_NETWORK: WorldPortalNode[] = [
  // 1. Gateway Portals
  {
    id: 'PORTAL_GATE_TO_GARAGE',
    name: 'Gateway to EV Showroom',
    label: 'EV SHOWROOM',
    subtitle: 'Main Central Hub',
    fromSector: 'SECURITY_CHECKPOINT',
    toSector: 'CENTRAL_GARAGE',
    position: [0, 0, 72],
    rotation: [0, 0, 0],
    color: '#00e5ff',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_GARAGE_TO_GATEWAY',
    name: 'Security Checkpoint Exit',
    label: 'SECURITY GATE',
    subtitle: 'Identity & Authentication',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'SECURITY_CHECKPOINT',
    position: [0, 0, 18],
    rotation: [0, Math.PI, 0],
    color: '#00e5ff',
    isReturnPortal: true,
  },

  // 2. Hub Outbound Portals from CENTRAL_GARAGE
  {
    id: 'PORTAL_GARAGE_TO_BOOKING',
    name: 'Booking Chamber Arch',
    label: 'BOOKING CHAMBER',
    subtitle: 'Chrono-Spatial Timeline',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'BOOKING_CHAMBER',
    position: [0, 0, -18],
    rotation: [0, 0, 0],
    color: '#00e5ff',
    requiredRole: 'ROLE_CO_OWNER',
  },
  {
    id: 'PORTAL_GARAGE_TO_CO_OWNERSHIP',
    name: 'Co-Ownership Portal',
    label: 'CO-OWNERSHIP',
    subtitle: 'Syndicate & Trust Registry',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'CO_OWNERSHIP_HALL',
    position: [18, 0, 18],
    rotation: [0, -Math.PI / 4, 0],
    color: '#ffab00',
    requiredRole: 'ROLE_CO_OWNER',
  },
  {
    id: 'PORTAL_GARAGE_TO_FINANCE',
    name: 'Finance & Expense Portal',
    label: 'FINANCE CENTER',
    subtitle: 'Expense Lab & Payments',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'ENERGY_FINANCE_CENTER',
    position: [-8, 0, -18],
    rotation: [0, 0, 0],
    color: '#00e676',
    requiredRole: 'ROLE_CO_OWNER',
  },
  {
    id: 'PORTAL_GARAGE_TO_VAULT',
    name: 'Shared Fund Vault Portal',
    label: 'SHARED FUND VAULT',
    subtitle: 'Syndicate Liquid Reserves',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'SHARED_FUND_VAULT',
    position: [-18, 0, -18],
    rotation: [0, Math.PI / 4, 0],
    color: '#ffab00',
    requiredRole: 'ROLE_CO_OWNER',
  },
  {
    id: 'PORTAL_GARAGE_TO_CONTRACT',
    name: 'Digital Contract Room Portal',
    label: 'CONTRACT ROOM',
    subtitle: 'Executive Legal Suite',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'DIGITAL_CONTRACT_ROOM',
    position: [18, 0, -18],
    rotation: [0, -Math.PI / 4, 0],
    color: '#60a5fa',
    requiredRole: 'ROLE_CO_OWNER',
  },
  {
    id: 'PORTAL_GARAGE_TO_DECISION',
    name: 'Decision Chamber Portal',
    label: 'DECISION CHAMBER',
    subtitle: 'Democratic Governance & Quorum',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'DECISION_CHAMBER',
    position: [18, 0, -8],
    rotation: [0, -Math.PI / 2, 0],
    color: '#818cf8',
    requiredRole: 'ROLE_CO_OWNER',
  },
  {
    id: 'PORTAL_GARAGE_TO_AI',
    name: 'AI Intelligence Nexus Portal',
    label: 'AI INTELLIGENCE',
    subtitle: 'Predictive Mobility Core',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'AI_INTELLIGENCE_CENTER',
    position: [18, 0, 0],
    rotation: [0, -Math.PI / 2, 0],
    color: '#c084fc',
    requiredRole: 'ROLE_CO_OWNER',
  },
  {
    id: 'PORTAL_GARAGE_TO_OPERATIONS',
    name: 'Operations Dispatch Gate',
    label: 'STAFF OPERATIONS',
    subtitle: 'Fleet Diagnostics & QR Dispatch',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'OPERATIONS_CENTER',
    position: [-18, 0, 0],
    rotation: [0, Math.PI / 2, 0],
    color: '#f97316',
    requiredRole: 'ROLE_STAFF',
  },
  {
    id: 'PORTAL_GARAGE_TO_WORKSHOP',
    name: 'Service Workshop Entrance',
    label: 'SERVICE WORKSHOP',
    subtitle: 'Hydraulic Lift & Repairs',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'SERVICE_WORKSHOP',
    position: [-18, 0, 18],
    rotation: [0, Math.PI / 4, 0],
    color: '#38bdf8',
    requiredRole: 'ROLE_STAFF',
  },
  {
    id: 'PORTAL_GARAGE_TO_DISPUTE',
    name: 'Dispute Room Arbitration Portal',
    label: 'DISPUTE ROOM',
    subtitle: 'Defect Holotank & Arbitration',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'DISPUTE_ROOM',
    position: [-18, 0, 24],
    rotation: [0, Math.PI / 4, 0],
    color: '#ff1744',
  },
  {
    id: 'PORTAL_GARAGE_TO_ADMIN',
    name: 'Orbital Elevator to Admin Command',
    label: 'ADMIN COMMAND',
    subtitle: 'Orbital Oversight Deck',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'ADMIN_COMMAND_CENTER',
    position: [0, 0, 2],
    rotation: [0, 0, 0],
    color: '#ffffff',
    requiredRole: 'ROLE_ADMIN',
  },

  // 3. Return Portals from Sectors back to CENTRAL_GARAGE
  {
    id: 'PORTAL_RETURN_CO_OWNERSHIP',
    name: 'Return to Central Garage',
    label: 'RETURN TO HUB',
    subtitle: 'Central Garage Showroom',
    fromSector: 'CO_OWNERSHIP_HALL',
    toSector: 'CENTRAL_GARAGE',
    position: [40, 0, 32],
    rotation: [0, Math.PI, 0],
    color: '#ffab00',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_RETURN_BOOKING',
    name: 'Return to Central Garage',
    label: 'RETURN TO HUB',
    subtitle: 'Central Garage Showroom',
    fromSector: 'BOOKING_CHAMBER',
    toSector: 'CENTRAL_GARAGE',
    position: [0, 0, -28],
    rotation: [0, Math.PI, 0],
    color: '#00e5ff',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_RETURN_FINANCE',
    name: 'Return to Central Garage',
    label: 'RETURN TO HUB',
    subtitle: 'Central Garage Showroom',
    fromSector: 'ENERGY_FINANCE_CENTER',
    toSector: 'CENTRAL_GARAGE',
    position: [0, 0, -68],
    rotation: [0, Math.PI, 0],
    color: '#00e676',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_RETURN_VAULT',
    name: 'Return to Central Garage',
    label: 'RETURN TO HUB',
    subtitle: 'Central Garage Showroom',
    fromSector: 'SHARED_FUND_VAULT',
    toSector: 'CENTRAL_GARAGE',
    position: [-40, 0, -68],
    rotation: [0, Math.PI, 0],
    color: '#ffab00',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_RETURN_CONTRACT',
    name: 'Return to Central Garage',
    label: 'RETURN TO HUB',
    subtitle: 'Central Garage Showroom',
    fromSector: 'DIGITAL_CONTRACT_ROOM',
    toSector: 'CENTRAL_GARAGE',
    position: [40, 0, -68],
    rotation: [0, Math.PI, 0],
    color: '#60a5fa',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_RETURN_DECISION',
    name: 'Return to Central Garage',
    label: 'RETURN TO HUB',
    subtitle: 'Central Garage Showroom',
    fromSector: 'DECISION_CHAMBER',
    toSector: 'CENTRAL_GARAGE',
    position: [40, 0, -28],
    rotation: [0, Math.PI, 0],
    color: '#818cf8',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_RETURN_AI',
    name: 'Return to Central Garage',
    label: 'RETURN TO HUB',
    subtitle: 'Central Garage Showroom',
    fromSector: 'AI_INTELLIGENCE_CENTER',
    toSector: 'CENTRAL_GARAGE',
    position: [40, 0, 12],
    rotation: [0, Math.PI, 0],
    color: '#c084fc',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_RETURN_OPERATIONS',
    name: 'Return to Central Garage',
    label: 'RETURN TO HUB',
    subtitle: 'Central Garage Showroom',
    fromSector: 'OPERATIONS_CENTER',
    toSector: 'CENTRAL_GARAGE',
    position: [-40, 0, 12],
    rotation: [0, Math.PI, 0],
    color: '#f97316',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_RETURN_WORKSHOP',
    name: 'Return to Central Garage',
    label: 'RETURN TO HUB',
    subtitle: 'Central Garage Showroom',
    fromSector: 'SERVICE_WORKSHOP',
    toSector: 'CENTRAL_GARAGE',
    position: [-40, 0, 28],
    rotation: [0, Math.PI, 0],
    color: '#38bdf8',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_RETURN_DISPUTE',
    name: 'Return to Central Garage',
    label: 'RETURN TO HUB',
    subtitle: 'Central Garage Showroom',
    fromSector: 'DISPUTE_ROOM',
    toSector: 'CENTRAL_GARAGE',
    position: [-40, 0, 68],
    rotation: [0, Math.PI, 0],
    color: '#ff1744',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_RETURN_ADMIN',
    name: 'Orbital Elevator Descent',
    label: 'DESCENT TO HUB',
    subtitle: 'Central Garage Showroom',
    fromSector: 'ADMIN_COMMAND_CENTER',
    toSector: 'CENTRAL_GARAGE',
    position: [0, 25, 4],
    rotation: [0, Math.PI, 0],
    color: '#ffffff',
    isReturnPortal: true,
  },
];

export function getPortalsForSector(sectorId: SectorId): WorldPortalNode[] {
  return PORTAL_NETWORK.filter((p) => p.fromSector === sectorId);
}

export function getPortalById(id: string): WorldPortalNode | undefined {
  return PORTAL_NETWORK.find((p) => p.id === id);
}
