import type { Vector3Tuple } from 'three';
import type { SectorId, UserRole } from './worldTypes';

export interface WorldPortalNode {
  id: string;
  name: string;
  label: string;
  subtitle: string;
  fromSector: SectorId;
  toSector: SectorId;
  position: Vector3Tuple;
  rotation: Vector3Tuple;
  color: string;
  requiredRole?: UserRole;
  isReturnPortal?: boolean;
}

export const PORTAL_NETWORK: WorldPortalNode[] = [
  // 1. Gateway Portals
  {
    id: 'PORTAL_GATE_TO_GARAGE',
    name: 'Cổng vào Garage Trung tâm',
    label: 'GARAGE TRUNG TÂM',
    subtitle: 'Khu Trưng bày Đội Xe điện',
    fromSector: 'SECURITY_CHECKPOINT',
    toSector: 'CENTRAL_GARAGE',
    position: [0, 0, 72],
    rotation: [0, 0, 0],
    color: '#00e5ff',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_GARAGE_TO_GATEWAY',
    name: 'Lối ra Cổng An ninh',
    label: 'CỔNG AN NINH',
    subtitle: 'Xác thực Danh tính & Đăng nhập',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'SECURITY_CHECKPOINT',
    position: [0, 0, 18],
    rotation: [0, Math.PI, 0],
    color: '#00e5ff',
    isReturnPortal: true,
  },

  // 2. Hub Outbound Portals from CENTRAL_GARAGE
  {
    id: 'PORTAL_GARAGE_TO_BOOKING',
    name: 'Cổng vào Phòng Đặt lịch',
    label: 'PHÒNG ĐẶT LỊCH',
    subtitle: 'Lịch sử dụng Xe & Khung giờ',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'BOOKING_CHAMBER',
    position: [0, 0, -18],
    rotation: [0, 0, 0],
    color: '#00e5ff',
    requiredRole: 'ROLE_CO_OWNER',
  },
  {
    id: 'PORTAL_GARAGE_TO_CO_OWNERSHIP',
    name: 'Cổng Sảnh Đồng sở hữu',
    label: 'SẢNH ĐỒNG SỞ HỮU',
    subtitle: 'Quản trị Nhóm & Tỷ lệ Cổ phần',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'CO_OWNERSHIP_HALL',
    position: [18, 0, 18],
    rotation: [0, -Math.PI / 4, 0],
    color: '#ffab00',
    requiredRole: 'ROLE_CO_OWNER',
  },
  {
    id: 'PORTAL_GARAGE_TO_FINANCE',
    name: 'Cổng Trung tâm Tài chính',
    label: 'TRUNG TÂM TÀI CHÍNH',
    subtitle: 'Phân bổ Chi phí & Thanh toán',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'ENERGY_FINANCE_CENTER',
    position: [-8, 0, -18],
    rotation: [0, 0, 0],
    color: '#00e676',
    requiredRole: 'ROLE_CO_OWNER',
  },
  {
    id: 'PORTAL_GARAGE_TO_VAULT',
    name: 'Cổng Kho Quỹ chung',
    label: 'KHO QUỸ CHUNG',
    subtitle: 'Kho bạc Quỹ chung & VietQR',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'SHARED_FUND_VAULT',
    position: [-18, 0, -18],
    rotation: [0, Math.PI / 4, 0],
    color: '#ffab00',
    requiredRole: 'ROLE_CO_OWNER',
  },
  {
    id: 'PORTAL_GARAGE_TO_CONTRACT',
    name: 'Cổng Phòng Hợp đồng Số',
    label: 'PHÒNG HỢP ĐỒNG',
    subtitle: 'Thỏa thuận Pháp lý & Chữ ký Số',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'DIGITAL_CONTRACT_ROOM',
    position: [18, 0, -18],
    rotation: [0, -Math.PI / 4, 0],
    color: '#60a5fa',
    requiredRole: 'ROLE_CO_OWNER',
  },
  {
    id: 'PORTAL_GARAGE_TO_DECISION',
    name: 'Cổng Phòng Biểu quyết',
    label: 'PHÒNG BIỂU QUYẾT',
    subtitle: 'Biểu quyết Dân chủ & Quản trị',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'DECISION_CHAMBER',
    position: [18, 0, -8],
    rotation: [0, -Math.PI / 2, 0],
    color: '#818cf8',
    requiredRole: 'ROLE_CO_OWNER',
  },
  {
    id: 'PORTAL_GARAGE_TO_AI',
    name: 'Cổng Trí tuệ Nhân tạo AI',
    label: 'TRÍ TUỆ NHÂN TẠO',
    subtitle: 'Khuyến nghị AI & Tối ưu hóa',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'AI_INTELLIGENCE_CENTER',
    position: [18, 0, 0],
    rotation: [0, -Math.PI / 2, 0],
    color: '#c084fc',
    requiredRole: 'ROLE_CO_OWNER',
  },
  {
    id: 'PORTAL_GARAGE_TO_OPERATIONS',
    name: 'Cổng Trung tâm Vận hành',
    label: 'TRUNG TÂM VẬN HÀNH',
    subtitle: 'Điều phối Xe & Quét mã QR',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'OPERATIONS_CENTER',
    position: [-18, 0, 0],
    rotation: [0, Math.PI / 2, 0],
    color: '#f97316',
    requiredRole: 'ROLE_STAFF',
  },
  {
    id: 'PORTAL_GARAGE_TO_WORKSHOP',
    name: 'Lối vào Xưởng Bảo trì',
    label: 'XƯỞNG BẢO TRÌ',
    subtitle: 'Cầu nâng & Kỹ thuật Sửa chữa',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'SERVICE_WORKSHOP',
    position: [-18, 0, 18],
    rotation: [0, Math.PI / 4, 0],
    color: '#38bdf8',
    requiredRole: 'ROLE_STAFF',
  },
  {
    id: 'PORTAL_GARAGE_TO_DISPUTE',
    name: 'Cổng Giải quyết Tranh chấp',
    label: 'GIẢI QUYẾT TRANH CHẤP',
    subtitle: 'Bàn Khiếm khuyết & Hòa giải',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'DISPUTE_ROOM',
    position: [-18, 0, 24],
    rotation: [0, Math.PI / 4, 0],
    color: '#ff1744',
  },
  {
    id: 'PORTAL_GARAGE_TO_ADMIN',
    name: 'Thang máy Quản trị Tối cao',
    label: 'ĐIỀU HÀNH QUẢN TRỊ',
    subtitle: '7 Lõi Quản trị Tối cao',
    fromSector: 'CENTRAL_GARAGE',
    toSector: 'ADMIN_COMMAND_CENTER',
    position: [0, 0, 2],
    rotation: [0, 0, 0],
    color: '#ffffff',
    requiredRole: 'ROLE_ADMIN',
  },

  // 3. Return Portals from Sectors back to CENTRAL_GARAGE
  {
    id: 'PORTAL_RETURN_CO_OWNERSHIP',
    name: 'Quay lại Garage Trung tâm',
    label: 'VỀ GARAGE TRUNG TÂM',
    subtitle: 'Khu Trưng bày Xe điện',
    fromSector: 'CO_OWNERSHIP_HALL',
    toSector: 'CENTRAL_GARAGE',
    position: [40, 0, 32],
    rotation: [0, Math.PI, 0],
    color: '#ffab00',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_RETURN_BOOKING',
    name: 'Quay lại Garage Trung tâm',
    label: 'VỀ GARAGE TRUNG TÂM',
    subtitle: 'Khu Trưng bày Xe điện',
    fromSector: 'BOOKING_CHAMBER',
    toSector: 'CENTRAL_GARAGE',
    position: [0, 0, -28],
    rotation: [0, Math.PI, 0],
    color: '#00e5ff',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_RETURN_FINANCE',
    name: 'Quay lại Garage Trung tâm',
    label: 'VỀ GARAGE TRUNG TÂM',
    subtitle: 'Khu Trưng bày Xe điện',
    fromSector: 'ENERGY_FINANCE_CENTER',
    toSector: 'CENTRAL_GARAGE',
    position: [0, 0, -68],
    rotation: [0, Math.PI, 0],
    color: '#00e676',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_RETURN_VAULT',
    name: 'Quay lại Garage Trung tâm',
    label: 'VỀ GARAGE TRUNG TÂM',
    subtitle: 'Khu Trưng bày Xe điện',
    fromSector: 'SHARED_FUND_VAULT',
    toSector: 'CENTRAL_GARAGE',
    position: [-40, 0, -68],
    rotation: [0, Math.PI, 0],
    color: '#ffab00',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_RETURN_CONTRACT',
    name: 'Quay lại Garage Trung tâm',
    label: 'VỀ GARAGE TRUNG TÂM',
    subtitle: 'Khu Trưng bày Xe điện',
    fromSector: 'DIGITAL_CONTRACT_ROOM',
    toSector: 'CENTRAL_GARAGE',
    position: [40, 0, -68],
    rotation: [0, Math.PI, 0],
    color: '#60a5fa',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_RETURN_DECISION',
    name: 'Quay lại Garage Trung tâm',
    label: 'VỀ GARAGE TRUNG TÂM',
    subtitle: 'Khu Trưng bày Xe điện',
    fromSector: 'DECISION_CHAMBER',
    toSector: 'CENTRAL_GARAGE',
    position: [40, 0, -28],
    rotation: [0, Math.PI, 0],
    color: '#818cf8',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_RETURN_AI',
    name: 'Quay lại Garage Trung tâm',
    label: 'VỀ GARAGE TRUNG TÂM',
    subtitle: 'Khu Trưng bày Xe điện',
    fromSector: 'AI_INTELLIGENCE_CENTER',
    toSector: 'CENTRAL_GARAGE',
    position: [40, 0, 12],
    rotation: [0, Math.PI, 0],
    color: '#c084fc',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_RETURN_OPERATIONS',
    name: 'Quay lại Garage Trung tâm',
    label: 'VỀ GARAGE TRUNG TÂM',
    subtitle: 'Khu Trưng bày Xe điện',
    fromSector: 'OPERATIONS_CENTER',
    toSector: 'CENTRAL_GARAGE',
    position: [-40, 0, 12],
    rotation: [0, Math.PI, 0],
    color: '#f97316',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_RETURN_WORKSHOP',
    name: 'Quay lại Garage Trung tâm',
    label: 'VỀ GARAGE TRUNG TÂM',
    subtitle: 'Khu Trưng bày Xe điện',
    fromSector: 'SERVICE_WORKSHOP',
    toSector: 'CENTRAL_GARAGE',
    position: [-40, 0, 28],
    rotation: [0, Math.PI, 0],
    color: '#38bdf8',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_RETURN_DISPUTE',
    name: 'Quay lại Garage Trung tâm',
    label: 'VỀ GARAGE TRUNG TÂM',
    subtitle: 'Khu Trưng bày Xe điện',
    fromSector: 'DISPUTE_ROOM',
    toSector: 'CENTRAL_GARAGE',
    position: [-40, 0, 68],
    rotation: [0, Math.PI, 0],
    color: '#ff1744',
    isReturnPortal: true,
  },
  {
    id: 'PORTAL_RETURN_ADMIN',
    name: 'Thang máy Hạ cánh Garage',
    label: 'XUỐNG GARAGE TRUNG TÂM',
    subtitle: 'Khu Trưng bày Xe điện',
    fromSector: 'ADMIN_COMMAND_CENTER',
    toSector: 'CENTRAL_GARAGE',
    position: [0, 25, 4],
    rotation: [0, Math.PI, 0],
    color: '#ffffff',
    isReturnPortal: true,
  },
];

export function getPortalsForSector(sectorId: SectorId): WorldPortalNode[] {
  return PORTAL_NETWORK.filter((p) => p.fromSector === sectorId);
}

export function getPortalById(id: string): WorldPortalNode | undefined {
  return PORTAL_NETWORK.find((p) => p.id === id);
}
